export const devMockHeaders = [
  "Name",
  "Start",
  "End",
  "Due",
  "Owner",
  "Status",
  "Notes",
  "Priority",
];

export const devMockRows = [
  {
    Name: "Discovery and requirements",
    Start: "05/08/2026",
    End: "09/08/2026",
    Due: "10/08/2026",
    Owner: "Ana",
    Status: "Concluído",
    Notes: "Stakeholder interviews finished.",
    Priority: "High",
  },
  {
    Name: "UI primitives extraction",
    Start: "10/08/2026",
    End: "",
    Due: "20/08/2026",
    Owner: "Bruno",
    Status: "Fazendo",
    Notes: "Migrating shared controls into components/ui.",
    Priority: "High",
  },
  {
    Name: "Regression test updates",
    Start: "12/08/2026",
    End: "",
    Due: "18/08/2026",
    Owner: "Carlos",
    Status: "Atrasado",
    Notes: "Waiting for final status color assertions.",
    Priority: "Medium",
  },
  {
    Name: "Apps Script bundle validation",
    Start: "21/08/2026",
    End: "",
    Due: "25/08/2026",
    Owner: "Dani",
    Status: "Não iniciado",
    Notes: "Run npm run create and inspect Sidebar output.",
    Priority: "Low",
  },
  {
    Name: "Custom status showcase",
    Start: "15/08/2026",
    End: "",
    Due: "23/08/2026",
    Owner: "Erika",
    Status: "Bloqueado",
    Notes: "Used to validate custom status chips and colors.",
    Priority: "High",
  },
];
